ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "googleUid" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatar" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "User_googleUid_key" ON "User"("googleUid");
