ALTER TABLE "NGO" ADD COLUMN IF NOT EXISTS "source" TEXT;
ALTER TABLE "NGO" ADD COLUMN IF NOT EXISTS "source_id" TEXT;
ALTER TABLE "NGO" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "NGO" ADD COLUMN IF NOT EXISTS "state" TEXT;
ALTER TABLE "NGO" ADD COLUMN IF NOT EXISTS "district" TEXT;
ALTER TABLE "NGO" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "NGO" ADD COLUMN IF NOT EXISTS "registration_number" TEXT;
ALTER TABLE "NGO" ADD COLUMN IF NOT EXISTS "type_of_ngo" TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS "NGO_source_id_key" ON "NGO"("source_id");
CREATE INDEX IF NOT EXISTS "NGO_source_idx" ON "NGO"("source");
CREATE INDEX IF NOT EXISTS "NGO_state_idx" ON "NGO"("state");
CREATE INDEX IF NOT EXISTS "NGO_district_idx" ON "NGO"("district");
