export const STROOPS_PER_XLM = 10_000_000;
export const COORDINATE_SCALE = 1_000_000;
export const DEFAULT_SOROBAN_RPC_URL = 'https://soroban-testnet.stellar.org';
export const CONFIRMATION_POLL_INTERVAL_MS = 2_000;
export const CONFIRMATION_MAX_ATTEMPTS = 30;

export const STELLAR_NETWORK_NAMES = {
  PUBLIC: 'public',
  MAINNET: 'mainnet',
  FUTURENET: 'futurenet',
  SANDBOX: 'sandbox',
  STANDALONE: 'standalone',
  TESTNET: 'testnet',
} as const;

export const CONTRACT_ENV_KEYS = {
  DONATION_REGISTRY: 'NEXT_PUBLIC_DONATION_REGISTRY_CONTRACT',
  DONATION_REGISTRY_ID: 'NEXT_PUBLIC_DONATION_REGISTRY_CONTRACT_ID',
  NGO_VERIFICATION_ID: 'NEXT_PUBLIC_NGO_VERIFICATION_CONTRACT_ID',
  IMPACT_ESCROW_ID: 'NEXT_PUBLIC_IMPACT_ESCROW_CONTRACT_ID',
  TOKEN_MANAGER_ID: 'NEXT_PUBLIC_TOKEN_MANAGER_CONTRACT_ID',
  NATIVE_TOKEN: 'NEXT_PUBLIC_NATIVE_TOKEN_CONTRACT',
  NATIVE_TOKEN_ID: 'NEXT_PUBLIC_NATIVE_TOKEN_CONTRACT_ID',
} as const;
